"""State object passed through the LangGraph extraction workflow."""

from typing import List, Literal, Optional

from pydantic import Field

from models.base import BaseModel
from models.datapoints import DataPoints
from models.sentence import Sentence


class ExtractionPass(BaseModel):
    """One keyword extraction attempt in the Phase 1 loop.

    Phase 1 can extract keywords more than once: the initial Keywords Extractor
    runs first, and the Supplementary Extractor can add missing keywords when
    the Comprehensive Checker says the result is incomplete. Keeping each pass
    lets us debug where a keyword came from and merge results deterministically.
    """

    # Which node produced this pass.
    source: Literal["keywords_extractor", "supplementary_extractor", "modifier"]

    # Loop iteration at the time this pass was produced.
    iteration: int

    # Skills extracted or modified by this pass.
    datapoints: DataPoints = Field(default_factory=lambda: DataPoints(skills=[]))

    # Optional model/debug explanation for why these datapoints were emitted.
    reason: Optional[str] = None


class ComprehensiveCheckResult(BaseModel):
    """Output of the Phase 1 Comprehensive Checker.

    The checker decides whether the merged keywords cover the important
    evidence in the document. If not, the workflow should call the Supplementary
    Extractor with the missing areas.
    """

    # True means Phase 1 can end and hand the merged datapoints to Phase 2.
    is_comprehensive: bool = False

    # Human-readable missing skills or concepts the supplementary extractor
    # should focus on.
    missing_keywords: List[str] = Field(default_factory=list)

    # Sentence ids that appear relevant but are not covered by current keywords.
    missing_sentence_ids: List[str] = Field(default_factory=list)

    # Optional debug score and explanation from the LLM checker.
    confidence: Optional[float] = None
    reason: Optional[str] = None


class ValidationIssue(BaseModel):
    """One issue found by the Phase 2 Validator."""

    # Stable id so the modifier can reference and fix a specific issue.
    issue_id: str

    # Severity allows future orchestration to ignore low-impact warnings while
    # blocking on errors.
    severity: Literal["warning", "error"] = "error"

    # Short explanation of what is wrong with the current keyword set.
    message: str

    # Optional skill names and sentence ids involved in the issue.
    skill_names: List[str] = Field(default_factory=list)
    referenced_sentence_ids: List[str] = Field(default_factory=list)

    # Suggested change for the Modifier node.
    suggested_fix: Optional[str] = None


class ValidationResult(BaseModel):
    """Output of the Phase 2 Validator.

    If ``is_valid`` is false, the workflow should call the Modifier and then run
    validation again until either valid or max iterations are reached.
    """

    # True means Phase 2 can finish and the datapoints are ready for matching.
    is_valid: bool = False

    # Concrete problems that must be fixed before matching.
    issues: List[ValidationIssue] = Field(default_factory=list)

    # Optional debug score and explanation from the LLM validator.
    confidence: Optional[float] = None
    reason: Optional[str] = None


class ExtractorState(BaseModel):
    """Mutable state passed through the extraction graph.

    The LangGraph workflow receives and returns this object at each node. Phase
    1 fills ``sentences`` and produces a comprehensive merged keyword set.
    Phase 2 validates and modifies that keyword set until it is ready for the
    downstream matcher.
    """

    # Core document context (shared across phases)

    # Human-readable marker for the current or last completed workflow node.
    # Example values: "phase1:preprocessor", "phase1:keywords_extractor",
    # "phase2:validator", "complete".
    step: str | None = None

    # Coarse workflow phase. This lets callers know whether the state is still
    # in extraction, validation, or ready for the matcher.
    phase: Literal["phase1", "phase2", "complete"] = "phase1"

    # Raw source document text for one side of the comparison. The worker runs
    # the graph separately for the JD text and the resume text.
    document: str

    # Sentence-level chunks generated by the preprocessor. Each sentence has a
    # stable id that extracted skills can cite.
    sentences: List[Sentence] = Field(default_factory=list)

    # Current merged keyword set. The matcher should read this field after Phase
    # 2 completes. Phase 1 merger and Phase 2 modifier both update it.
    datapoints: DataPoints = Field(default_factory=lambda: DataPoints(skills=[]))

    # History of all extraction/modification passes. This supports the complete
    # Keywords Extractor flow and makes the LLM loop auditable.
    extraction_history: List[ExtractionPass] = Field(default_factory=list)

    # Phase 1 loop counter for Keywords Extractor -> Merger -> Comprehensive
    # Checker -> Supplementary Extractor. The graph should stop when the checker
    # passes or this reaches max_phase1_iterations.
    phase1_iteration: int = 0
    max_phase1_iterations: int = 3

    # Latest result from the Comprehensive Checker.
    comprehensive_check: ComprehensiveCheckResult | None = None

    # Phase 2 loop counter for Validator -> Modifier. The graph should stop when
    # validation passes or this reaches max_phase2_iterations.
    phase2_iteration: int = 0
    max_phase2_iterations: int = 3

    # Latest result from the Validator.
    validation_result: ValidationResult | None = None

    def record_extraction_pass(
        self,
        source: Literal["keywords_extractor", "supplementary_extractor", "modifier"],
        datapoints: DataPoints,
        reason: Optional[str] = None,
    ) -> None:
        """Append an extraction/modification pass and update current datapoints.

        Future extractor nodes should call this after they produce new or
        modified keywords. The merger node can still replace ``datapoints``
        directly after combining multiple passes.
        """

        self.extraction_history.append(
            ExtractionPass(
                source=source,
                iteration=(
                    self.phase1_iteration
                    if self.phase == "phase1"
                    else self.phase2_iteration
                ),
                datapoints=datapoints,
                reason=reason,
            )
        )
        self.datapoints = datapoints

    def ready_for_phase2(self) -> bool:
        """Return whether Phase 1 has produced comprehensive keywords."""

        return bool(
            self.comprehensive_check
            and self.comprehensive_check.is_comprehensive
        )

    def ready_for_matcher(self) -> bool:
        """Return whether Phase 2 has validated the keyword set."""

        return bool(self.validation_result and self.validation_result.is_valid)
