"""Sentence models used by the preprocessing phase."""

from typing import List
from pydantic import ConfigDict

from models.base import BaseModel


class Sentence(BaseModel):
    """One preprocessed sentence with a stable id.

    Skill extraction should refer back to these ids instead of copying full
    evidence text into every result.
    """

    model_config = ConfigDict(extra="forbid")

    # Numeric ids are generated by the current preprocessor, but the type also
    # allows strings so future chunkers can use UUIDs or source-specific ids.
    id: str | int

    # Clean sentence text extracted from the original document.
    sentence: str


class RawSentences(BaseModel):
    """Strict LLM output schema for the sentence-splitting node."""

    model_config = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "required": ["sentences"]
        },
    )

    # The LLM returns plain strings first; the preprocessor wraps them into
    # Sentence objects with ids after parsing.
    sentences: List[str]
